/* --- USERS --- */
export const LOAD_USERS_INIT = 'LOAD_USERS_INIT';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR';

/* --- FORMS --- */
export const LOAD_PERSONS_LIST = 'LOAD_PERSONS_LIST';
export const UPDATE_PERSONS_LIST = 'UPDATE_PERSONS_LIST';